### ISSUE TITLE
RSpec advice on Rack::Config in rails

### ISSUE THREAD

**Issue by christopherhein** [ruby-grape/grape-rabl#2]
With my current setup using spork, rspec, & rails, it seems as though anytime I'm trying to use grape-rabl, it errors with "Use Rack::Config to set 'api.tilt.root' in config.ru" which I have defined in the config.ru as such:

``` ruby
require 'grape/rabl'

use Rack::Config do |env|
  env['api.tilt.root'] = Rails.root.join "app", "views", "api"
end
```

and in my specs i'm using:

``` ruby
  describe "GET /system/versions" do
    it "returns an array with v1 inside it" do
      get "/system/versions"
      response.status.should eq 200
      JSON.parse(response.body).should == ["v1"]
    end
  end
```

am I missing som necessary information for using rspec with grape-rabl?

**Comment by VitorHP** [comment]
+1 

Same here. I'm not using rails tough. My config.ru has the Rack::Config stuff, but tests fail with "Use Rack::Config to set 'api.tilt.root' in config.ru"
