### ISSUE TITLE
Fallback rendering should use the default formatter

### ISSUE THREAD

**Issue by chrisbloom7** [ruby-grape/grape-rabl#33]
Setup:

```
module RailsApp
  class API < Grape::API
    prefix :api
    format :xml
    formatter :xml, Grape::Formatter::Rabl
    content_type :xml, 'application/xml'
    default_format :xml

    resource :client_authorizations do
      post '/' do
        client_authorization = ClientAuthorization.new params[:clientAuthorization]
        if client_authorization.save
          @reference = OpenStruct.new({status: "OK", reference: client_authorization.id})
          render rabl: "client_authorizations"
        else
          client_authorization.errors
        end
      end
    end
  end
end
```

If the post is successful, it renders the RABL template as expected. If not, it renders the errors as a json string: `{"current_date_begins":["is not a valid date"]}`. Based on the example in the README (line 152), I was expecting it to render using the default XML formatter. If I comment out the line `formatter :xml, Grape::Formatter::Rabl` the errors are rendered as XML as expected. Looking at the source, I see it's hardcoded to fallback to the JSON formatter. Ideally, this should pick up the default_format formatter, or should be configurable.

**Comment by dblock** [comment]
Fixed via https://github.com/ruby-grape/grape-rabl/pull/34
