### ISSUE TITLE
CI not configured

### ISSUE THREAD

**Issue by olleolleolle** [ruby-grape/grape-rabl#49]
The badge in the README shows as missing.

**Comment by dblock** [comment]
I hit "activate" on it. Let's bring this repo up to date with rubies and what not and see if it can build?

**Comment by olleolleolle** [comment]
**Update**: The thing activated and is building.

**Comment by olleolleolle** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/211/61225772-89d97500-a721-11e9-8ad7-fbc2c8872a03.png">

Fixed!
